from __future__ import annotations

from reviewpilot.analyzer.schemas import ReviewFinding, ReviewReport, Severity
from reviewpilot.language import ReportLanguage


def render_report_markdown(report: ReviewReport, report_language: ReportLanguage = "en") -> str:
    labels = _labels(report_language)
    lines: list[str] = []
    lines.append(f"# {labels['report']}")
    lines.append("")
    lines.append(f"## {labels['summary']}")
    lines.append("")
    lines.append(report.summary)
    lines.append("")
    lines.append(f"## {labels['merge_conclusion']}")
    lines.append("")
    lines.append(report.merge_conclusion)
    lines.append("")

    if report.risks:
        lines.append(f"## {labels['risks']}")
        lines.append("")
        for finding in report.risks:
            _render_finding_markdown(finding, lines, labels)

    if report.inline_reviews:
        lines.append(f"## {labels['inline_reviews']}")
        lines.append("")
        for finding in report.inline_reviews:
            _render_finding_markdown(finding, lines, labels)

    return "\n".join(lines)


def _render_finding_markdown(
    finding: ReviewFinding,
    lines: list[str],
    labels: dict[str, str],
) -> None:
    conf_pct = f"{finding.confidence:.0%}"
    lines.append(f"### [{finding.severity}] {finding.title} ({labels['confidence']}: {conf_pct})")
    lines.append("")
    if finding.file_path:
        location = f"`{finding.file_path}`"
        if finding.line_number:
            location += f":{finding.line_number}"
        lines.append(f"- **{labels['location']}:** {location}")
    lines.append(f"- **{labels['evidence']}:** {finding.evidence}")
    lines.append(f"- **{labels['recommendation']}:** {finding.recommendation}")
    lines.append("")


def render_comment_body(report: ReviewReport, report_language: ReportLanguage = "en") -> str:
    labels = _labels(report_language)
    lines: list[str] = []
    lines.append(f"## ReviewPilot {labels['report']}")
    lines.append("")
    lines.append(f"**{labels['merge_conclusion']}:** {report.merge_conclusion}")
    lines.append("")

    for sev, label in [(Severity.p0, "P0"), (Severity.p1, "P1"), (Severity.p2, "P2")]:
        findings = [f for f in report.risks + report.inline_reviews if f.severity == sev]
        if findings:
            lines.append(f"### {label} {labels['findings']} ({len(findings)})")
            lines.append("")
            for f in findings:
                conf_pct = f"{f.confidence:.0%}"
                location = ""
                if f.file_path:
                    location = f"`{f.file_path}`"
                    if f.line_number:
                        location += f":{f.line_number}"
                    location = f" ({location})"
                lines.append(
                    f"- **[{f.severity}] {f.title}**{location} - "
                    f"{labels['confidence']}: {conf_pct}"
                )
            lines.append("")

    lines.append("---")
    footer = "Review generated by ReviewPilot"
    if report_language == "zh":
        footer = "由 ReviewPilot 生成的审查报告"
    lines.append(f"*{footer}*")
    return "\n".join(lines)


def _labels(report_language: ReportLanguage) -> dict[str, str]:
    if report_language == "zh":
        return {
            "report": "审查报告",
            "summary": "摘要",
            "merge_conclusion": "合并结论",
            "risks": "风险",
            "inline_reviews": "行内审查",
            "confidence": "置信度",
            "location": "位置",
            "evidence": "证据",
            "recommendation": "建议",
            "findings": "发现",
        }
    return {
        "report": "Review Report",
        "summary": "Summary",
        "merge_conclusion": "Merge Conclusion",
        "risks": "Risks",
        "inline_reviews": "Inline Reviews",
        "confidence": "confidence",
        "location": "Location",
        "evidence": "Evidence",
        "recommendation": "Recommendation",
        "findings": "Findings",
    }
