from __future__ import annotations

from reviewpilot.analyzer.schemas import ReviewFinding, ReviewReport, Severity


def render_report_markdown(report: ReviewReport) -> str:
    lines: list[str] = []
    lines.append("# Review Report")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(report.summary)
    lines.append("")
    lines.append("## Merge Conclusion")
    lines.append("")
    lines.append(report.merge_conclusion)
    lines.append("")

    if report.risks:
        lines.append("## Risks")
        lines.append("")
        for finding in report.risks:
            _render_finding_markdown(finding, lines)

    if report.inline_reviews:
        lines.append("## Inline Reviews")
        lines.append("")
        for finding in report.inline_reviews:
            _render_finding_markdown(finding, lines)

    return "\n".join(lines)


def _render_finding_markdown(finding: ReviewFinding, lines: list[str]) -> None:
    conf_pct = f"{finding.confidence:.0%}"
    lines.append(f"### [{finding.severity}] {finding.title} (confidence: {conf_pct})")
    lines.append("")
    if finding.file_path:
        location = f"`{finding.file_path}`"
        if finding.line_number:
            location += f":{finding.line_number}"
        lines.append(f"- **Location:** {location}")
    lines.append(f"- **Evidence:** {finding.evidence}")
    lines.append(f"- **Recommendation:** {finding.recommendation}")
    lines.append("")


def render_comment_body(report: ReviewReport) -> str:
    lines: list[str] = []
    lines.append("## ReviewPilot Report")
    lines.append("")
    lines.append(f"**Merge Conclusion:** {report.merge_conclusion}")
    lines.append("")

    for sev, label in [(Severity.p0, "P0"), (Severity.p1, "P1"), (Severity.p2, "P2")]:
        findings = [f for f in report.risks + report.inline_reviews if f.severity == sev]
        if findings:
            lines.append(f"### {label} Findings ({len(findings)})")
            lines.append("")
            for f in findings:
                conf_pct = f"{f.confidence:.0%}"
                location = ""
                if f.file_path:
                    location = f"`{f.file_path}`"
                    if f.line_number:
                        location += f":{f.line_number}"
                    location = f" ({location})"
                lines.append(f"- **[{f.severity}] {f.title}**{location} — confidence: {conf_pct}")
            lines.append("")

    lines.append("---")
    lines.append("*Review generated by ReviewPilot*")
    return "\n".join(lines)
